### ISSUE TITLE
Where should the data.json file be placed?

### ISSUE THREAD

**Issue by bakboem** [Sach97/scrapy.dart#2]
E/flutter (31339): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: FileSystemException: Cannot open file, path = 'data.json' (OS Error: Read-only file system, errno = 30)

**Comment by Sach97** [comment]
Hi @bakboem, I fixed your issue with the new version (not yet published) git clone the new version and see if the example works for you

**Comment by Sach97** [comment]
Sorry for the delay, I cleaned up the code and removed a dependency just published v 0.0.3
